language: node_js
node_js:
- stable

before_install:
  - npm install -g bower
  - npm install -g polymer-cli

install: bower install

script: polymer build

deploy:
  provider: pages
  name: "Travis CI Deployment Bot"
  email: "TheUWICS@users.noreply.github.com"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build/default/
  on:
    brach: master
