language: node_js
node_js:
- stable

before_install:
  - npm install -g bower
  - npm install -g polymer-cli

install: bower install

script: polymer build

after_success: |
  if [ -n "$GITHUB_TOKEN" ]; then
    cd "$TRAVIS_BUILD_DIR"
    git clone https://github.com/TheUWICS/TheUWICS.github.io.git deploy
    cd deploy
    git checkout -b master
    rm *
    cd ../
    cp -r build/default deploy
    cd repo
    git add .
    git -c user.name='Travis CI Deployment Bot' -c user.email='TheUWICS@users.noreply.github.com' commit -m 'Deploying'
    git push -f -q https://TheUWICS:$GITHUB_TOKEN@github.com/TheUWICS/TheUWICS.github.io master &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi


# deploy:
#   provider: pages
#   name: "Travis CI Deployment Bot"
#   email: "TheUWICS@users.noreply.github.com"
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#   local_dir: build/default/
#   on:
#     brach: dev
