language: node_js
node_js:
- stable

before_install:
  - npm install -g bower
  - npm install -g polymer-cli

install: bower install

script: polymer build

after_success: |
  if [ -n "$GITHUB_TOKEN" ]; then
    cd "$TRAVIS_BUILD_DIR"
    ls
    mkdir web
    cd web
    git clone https://github.com/TheUWICS/TheUWICS.github.io.git
    git checkout -b dev
    polymer build
    mv -rf .git/ build/default/.git/
    cd build/default/
    git add .
    git -c user.name='Travis CI Deployment Bot' -c user.email='TheUWICS@users.noreply.github.com' commit -m init
    git push -f -q https://TheUWICS:$GITHUB_TOKEN@github.com/TheUWICS/TheUWICS.github.io master &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
    ls
  fi
